### PR TITLE
Added CSS

### PR DESCRIPTION
**Pull request by alexbrandsen**
Added a css folder and file, and added the call to the css file and custom fonts in the header.html file.

### CODE REVIEW

**Comment by bencomp** [comment]
Thanks, @alexbrandsen! Sorry for the delay of my response.

Would it be possible to use a more generally available font, so that we don't need to rely on Google Fonts?

**Comment by alexbrandsen** [comment]
Yes of course, have updated and pushed it!

**Comment by bencomp** [comment]
@alexbrandsen Sorry for keeping you waiting and thanks again :)

**Comment by alexbrandsen** [comment]
Happy to help!

**Pull request merged**
